export enum AgentState {
  IDLE = "IDLE",
  LISTENING = "LISTENING",
  PROCESSING = "PROCESSING",
  CLARIFYING = "CLARIFYING",
  CONVERSING = "CONVERSING",
  PROPOSING = "PROPOSING",
  AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION",
  NAVIGATING = "NAVIGATING",
  EXECUTING = "EXECUTING",
  COMPLETED = "COMPLETED",
  ERROR = "ERROR",
}
